export const EventType = {
  CAMPAIGN_STARTED: "CAMPAIGN_STARTED",
  STAGE_UNLOCKED: "STAGE_UNLOCKED",
  STAGE_COMPLETED: "STAGE_COMPLETED",
  ARTIFACT_GENERATED: "ARTIFACT_GENERATED",
  SERVICE_STARTED: "SERVICE_STARTED",
  SERVICE_STOPPED: "SERVICE_STOPPED",
  SUBMISSION_RECEIVED: "SUBMISSION_RECEIVED",
  SUBMISSION_PASSED: "SUBMISSION_PASSED",
  SUBMISSION_FAILED: "SUBMISSION_FAILED",
  HINT_USED: "HINT_USED",
  FINDING_CONFIRMED: "FINDING_CONFIRMED",
  ENVIRONMENT_RESET: "ENVIRONMENT_RESET",
} as const;
export type EventType = (typeof EventType)[keyof typeof EventType];

export const JobType = {
  GRADE_SUBMISSION: "GRADE_SUBMISSION",
  PROVISION_ENVIRONMENT: "PROVISION_ENVIRONMENT",
  GENERATE_ARTIFACT: "GENERATE_ARTIFACT",
  PROCESS_EVENT: "PROCESS_EVENT",
} as const;
export type JobType = (typeof JobType)[keyof typeof JobType];
